version: "3.9"

services:
  db:
    image: postgres:15
    container_name: gestao-pessoas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030   # 🔒 defina uma senha forte
      POSTGRES_DB: gestao_pessoas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestao-network

  app:
    build: .
    container_name: gestao-pessoas-app
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=gestao_pessoas;Username=postgres;Password=102030
    ports:
      - "5000:5000"
    networks:
      - gestao-network

volumes:
  postgres_data:

networks:
  gestao-network:
