name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Diretório da aplicação na EC2
            mkdir -p ~/app
            cd ~/app

            # Build da imagem
            docker build -t gestao-pessoas-app .

            # Para e remove container antigo (se existir)
            docker stop gestao-pessoas-app || true
            docker rm gestao-pessoas-app || true

            # Roda container mapeando a porta 5000
            docker run -d --name gestao-pessoas-app -p 5000:5000 gestao-pessoas-app
